spring.application.name=chessEngine


claude.api.key=${CLAUDE_API_KEY}
spring.ai.openai.api-key=${OPENAI_API_KEY}
spring.ai.openai.chat.options.model=${OPENAI_MODEL}
spring.ai.openai.chat.options.reasoning-effort=${OPENAI_EFFORT}
spring.ai.anthropic.api-key=${CLAUDE_API_KEY}
spring.ai.anthropic.chat.options.model=${ANTHROPIC_MODEL}